{% set name = "guanine-crystal-analysis" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/guanine-crystal-analysis-{{ version }}.tar.gz
  sha256: 105c0b6b0fc825476a94931a9992926cc17eb62518e343598eb0b12f7595d8e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - apoc-backend
    - magicgui
    - napari-simpleitk-image-processing
    - napari-skimage-regionprops
    - napari-workflows
    - numpy
    - pandas
    - pyclesperanto-prototype
    - python >=3.8
    - qtpy
    - scikit-image
    - scikit-learn

test:
  imports:
    - guanine_crystal_analysis
  commands:
    - pip list
    # - pip check  # not working due to napari-assistant
  requires:
    - pip
    - pocl

about:
  home: https://github.com/biapol/guanine-crystal-analysis
  summary: A plugin for the guanine crystal segmentation, classification and characterization in the zebrafish eye
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
    - marabuuu
